import os
import psycopg

DATABASE_URL = os.environ.get("DATABASE_URL")


def get_connection():
    if not DATABASE_URL:
        raise RuntimeError("DATABASE_URL environment variable is not set")
    return psycopg.connect(DATABASE_URL)


def add_skill(name):
    conn = get_connection()
    conn.execute(
        "INSERT INTO skills (name) VALUES (%s) ON CONFLICT (name) DO NOTHING",
        (name,)
    )
    conn.commit()
    conn.close()


def get_skills():
    conn = get_connection()
    skills = conn.execute("SELECT * FROM skills").fetchall()
    conn.close()
    return skills


def save_resume(filename):
    conn = get_connection()
    cursor = conn.execute(
        "INSERT INTO resumes (filename) VALUES (%s) RETURNING id",
        (filename,)
    )
    resume_id = cursor.fetchone()[0]
    conn.commit()
    conn.close()
    return resume_id


def save_resume_skills(resume_id, skill_names):
    conn = get_connection()
    for skill_name in skill_names:
        row = conn.execute(
            "SELECT id FROM skills WHERE name = %s",
            (skill_name,)
        ).fetchone()
        if row:
            conn.execute(
                "INSERT INTO resume_skills (resume_id, skill_id) VALUES (%s, %s) ON CONFLICT DO NOTHING",
                (resume_id, row[0])
            )
    conn.commit()
    conn.close()


def save_job(title, description):
    conn = get_connection()
    cursor = conn.execute(
        "INSERT INTO jobs (title, description) VALUES (%s, %s) RETURNING id",
        (title, description)
    )
    job_id = cursor.fetchone()[0]
    conn.commit()
    conn.close()
    return job_id


def save_job_skills(job_id, skill_names):
    conn = get_connection()
    for skill_name in skill_names:
        row = conn.execute(
            "SELECT id FROM skills WHERE name = %s",
            (skill_name,)
        ).fetchone()
        if row:
            conn.execute(
                "INSERT INTO job_skills (job_id, skill_id) VALUES (%s, %s) ON CONFLICT DO NOTHING",
                (job_id, row[0])
            )
    conn.commit()
    conn.close()


def init_database():
    conn = get_connection()
    with open("database/schema.sql", "r", encoding="utf-8") as file:
        schema = file.read()
    schema = schema.replace(
        "INTEGER PRIMARY KEY AUTOINCREMENT",
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    )
    for statement in schema.split(";"):
        statement = statement.strip()
        if statement:
            conn.execute(statement)
    conn.commit()
    conn.close()


init_database()
